name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8    
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Setup DVC
      uses: actions/checkout@v2
    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRET: ${{ secrets.SECRET }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.ss
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    - name: DVC
      run: |
        dvc init --no-scm -f
        dvc remote add -d remote_storage gs://dtu_mlops/
        dvc remote modify remote_storage gdrive_use_service_account true
        dvc remote modify remote_storage --local credentialpath '/.github/scripts/secret.json'
    - name: DVC pull
      run: |
        dvc pull
    - name: Test with pytest  
      run: |
        pip install pytest
        pytest tests/
