name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8    
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    - name: DVC
      run: |
        git init
        dvc init
        
        dvc remote add myremote gdrive://root
        dvc remote modify myremote --local gdrive_use_service_account true
        dvc remote modify myremote --local gdrive_service_account_json_file_path ${{ secrets.Cloud}}
        
        date > file
        dvc add file
        dvc push --remote myremote
    - name: Test with pytest  
      run: |
        pip install pytest
        pytest tests/
